service: products-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-north-1

plugins:
  - serverless-webpack

custom: # Add custom section and include webpack configuration
    webpack:
      webpackConfig: 'webpack.config.js'
      includeModules: false

functions:
  getProducts:
    handler: handler.getProducts
    events:
      - http:
          path: /products
          method: get
          cors: true
  getProduct:
    handler: handler.getProduct
    events:
      - http:
          path: /products/{id}
          method: get
